services:
  postgres:
    build: ./docker/postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./docker/postgres/.volume:/var/lib/postgresql
    networks:
      - tlc_trip_pipelines

  pgweb:
    build: ./docker/pgweb
    container_name: pgweb
    restart: always
    environment:
      - PGWEB_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DATABASE}?sslmode=disable
    ports:
      - "${PGWEB_PORT}:8081"
    depends_on:
      - postgres
    networks:
      - tlc_trip_pipelines

  tlc_pipelines:
    build: ./docker/tlc_pipelines
    container_name: tlc_pipelines
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - ./docker/tlc_pipelines/app:/app
    networks:
      - tlc_trip_pipelines

networks:
  tlc_trip_pipelines:
    driver: bridge